AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Quarkus - quarkus-amazon-lambda-common-deployment
Globals:
  Api:
    EndpointConfiguration: REGIONAL
    BinaryMediaTypes:
      - "*/*"

Parameters:
  SimpleBotFnName:
    Type: String
    Description: The name of the Lambda function
    Default: "simple-bot-codehook"

Resources:
  SimpleBotFn:
    Type: AWS::Serverless::Function
    Properties:
      Handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest
      Runtime: java11
      CodeUri: target/function.zip
      MemorySize: 256
      Timeout: 60
      Policies: AWSLambdaBasicExecutionRole

Outputs:

  SimpleBotFnArn:
    Description: The ARN of the Lambda function
    Value: !GetAtt "SimpleBotFn.Arn"
    Export:
      Name: !Sub "${AWS::StackName}-SimpleBotFnArn"

  SimpleBotFnName:
    Description: The Name of the Lambda function
    Value: !Ref "SimpleBotFnName"
    Export:
      Name: !Sub "${AWS::StackName}-SimpleBotFnName"
